name: Deploy main page

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download libmpegh
        run: |
          mkdir -p js/libmpegh
          curl -L -o libmpegh.zip https://run4r-ses.github.io/libmpegh_builder/downloads/libmpegh-build-wasm.zip
          unzip -o libmpegh.zip -d js/libmpegh
          rm libmpegh.zip

      - name: Patch files
        run: |
          python3 patch.py
          rm patch.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
